version: "3.9"

services:
  
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    env_file: .env
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    networks:
      - otree

  otree:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    command: [ './compose/production/start.sh' ]
    container_name: otree
    env_file: .env
    networks:
      - otree
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  otree:
